spring:
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true